/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as MultiAgentRouteImport } from './routes/multi-agent'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CheckpointsRouteImport } from './routes/checkpoints'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as ProjectsNameRouteImport } from './routes/projects.$name'
import { Route as MemoriesIdRouteImport } from './routes/memories.$id'
import { Route as DocsApiSseRouteImport } from './routes/docs.api.sse'
import { Route as DocsApiRestRouteImport } from './routes/docs.api.rest'
import { Route as DocsAdvancedTroubleshootingRouteImport } from './routes/docs.advanced.troubleshooting'
import { Route as DocsAdvancedArchitectureRouteImport } from './routes/docs.advanced.architecture'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiAgentRoute = MultiAgentRouteImport.update({
  id: '/multi-agent',
  path: '/multi-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckpointsRoute = CheckpointsRouteImport.update({
  id: '/checkpoints',
  path: '/checkpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemoriesRoute,
} as any)
const ProjectsNameRoute = ProjectsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ProjectsRoute,
} as any)
const MemoriesIdRoute = MemoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MemoriesRoute,
} as any)
const DocsApiSseRoute = DocsApiSseRouteImport.update({
  id: '/api/sse',
  path: '/api/sse',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRestRoute = DocsApiRestRouteImport.update({
  id: '/api/rest',
  path: '/api/rest',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAdvancedTroubleshootingRoute =
  DocsAdvancedTroubleshootingRouteImport.update({
    id: '/advanced/troubleshooting',
    path: '/advanced/troubleshooting',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsAdvancedArchitectureRoute =
  DocsAdvancedArchitectureRouteImport.update({
    id: '/advanced/architecture',
    path: '/advanced/architecture',
    getParentRoute: () => DocsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/checkpoints': typeof CheckpointsRoute
  '/docs': typeof DocsRouteWithChildren
  '/guide': typeof GuideRoute
  '/mcp': typeof McpRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/multi-agent': typeof MultiAgentRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/memories/$id': typeof MemoriesIdRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/memories/': typeof MemoriesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/docs/advanced/architecture': typeof DocsAdvancedArchitectureRoute
  '/docs/advanced/troubleshooting': typeof DocsAdvancedTroubleshootingRoute
  '/docs/api/rest': typeof DocsApiRestRoute
  '/docs/api/sse': typeof DocsApiSseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/checkpoints': typeof CheckpointsRoute
  '/docs': typeof DocsRouteWithChildren
  '/guide': typeof GuideRoute
  '/mcp': typeof McpRoute
  '/metrics': typeof MetricsRoute
  '/multi-agent': typeof MultiAgentRoute
  '/playground': typeof PlaygroundRoute
  '/settings': typeof SettingsRoute
  '/memories/$id': typeof MemoriesIdRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/memories': typeof MemoriesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/docs/advanced/architecture': typeof DocsAdvancedArchitectureRoute
  '/docs/advanced/troubleshooting': typeof DocsAdvancedTroubleshootingRoute
  '/docs/api/rest': typeof DocsApiRestRoute
  '/docs/api/sse': typeof DocsApiSseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/checkpoints': typeof CheckpointsRoute
  '/docs': typeof DocsRouteWithChildren
  '/guide': typeof GuideRoute
  '/mcp': typeof McpRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/metrics': typeof MetricsRoute
  '/multi-agent': typeof MultiAgentRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/memories/$id': typeof MemoriesIdRoute
  '/projects/$name': typeof ProjectsNameRoute
  '/memories/': typeof MemoriesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/docs/advanced/architecture': typeof DocsAdvancedArchitectureRoute
  '/docs/advanced/troubleshooting': typeof DocsAdvancedTroubleshootingRoute
  '/docs/api/rest': typeof DocsApiRestRoute
  '/docs/api/sse': typeof DocsApiSseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/checkpoints'
    | '/docs'
    | '/guide'
    | '/mcp'
    | '/memories'
    | '/metrics'
    | '/multi-agent'
    | '/playground'
    | '/projects'
    | '/settings'
    | '/memories/$id'
    | '/projects/$name'
    | '/memories/'
    | '/projects/'
    | '/docs/advanced/architecture'
    | '/docs/advanced/troubleshooting'
    | '/docs/api/rest'
    | '/docs/api/sse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/checkpoints'
    | '/docs'
    | '/guide'
    | '/mcp'
    | '/metrics'
    | '/multi-agent'
    | '/playground'
    | '/settings'
    | '/memories/$id'
    | '/projects/$name'
    | '/memories'
    | '/projects'
    | '/docs/advanced/architecture'
    | '/docs/advanced/troubleshooting'
    | '/docs/api/rest'
    | '/docs/api/sse'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/checkpoints'
    | '/docs'
    | '/guide'
    | '/mcp'
    | '/memories'
    | '/metrics'
    | '/multi-agent'
    | '/playground'
    | '/projects'
    | '/settings'
    | '/memories/$id'
    | '/projects/$name'
    | '/memories/'
    | '/projects/'
    | '/docs/advanced/architecture'
    | '/docs/advanced/troubleshooting'
    | '/docs/api/rest'
    | '/docs/api/sse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  CheckpointsRoute: typeof CheckpointsRoute
  DocsRoute: typeof DocsRouteWithChildren
  GuideRoute: typeof GuideRoute
  McpRoute: typeof McpRoute
  MemoriesRoute: typeof MemoriesRouteWithChildren
  MetricsRoute: typeof MetricsRoute
  MultiAgentRoute: typeof MultiAgentRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-agent': {
      id: '/multi-agent'
      path: '/multi-agent'
      fullPath: '/multi-agent'
      preLoaderRoute: typeof MultiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkpoints': {
      id: '/checkpoints'
      path: '/checkpoints'
      fullPath: '/checkpoints'
      preLoaderRoute: typeof CheckpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/memories/': {
      id: '/memories/'
      path: '/'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof MemoriesRoute
    }
    '/projects/$name': {
      id: '/projects/$name'
      path: '/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof ProjectsNameRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/memories/$id': {
      id: '/memories/$id'
      path: '/$id'
      fullPath: '/memories/$id'
      preLoaderRoute: typeof MemoriesIdRouteImport
      parentRoute: typeof MemoriesRoute
    }
    '/docs/api/sse': {
      id: '/docs/api/sse'
      path: '/api/sse'
      fullPath: '/docs/api/sse'
      preLoaderRoute: typeof DocsApiSseRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api/rest': {
      id: '/docs/api/rest'
      path: '/api/rest'
      fullPath: '/docs/api/rest'
      preLoaderRoute: typeof DocsApiRestRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/advanced/troubleshooting': {
      id: '/docs/advanced/troubleshooting'
      path: '/advanced/troubleshooting'
      fullPath: '/docs/advanced/troubleshooting'
      preLoaderRoute: typeof DocsAdvancedTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/advanced/architecture': {
      id: '/docs/advanced/architecture'
      path: '/advanced/architecture'
      fullPath: '/docs/advanced/architecture'
      preLoaderRoute: typeof DocsAdvancedArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsAdvancedArchitectureRoute: typeof DocsAdvancedArchitectureRoute
  DocsAdvancedTroubleshootingRoute: typeof DocsAdvancedTroubleshootingRoute
  DocsApiRestRoute: typeof DocsApiRestRoute
  DocsApiSseRoute: typeof DocsApiSseRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAdvancedArchitectureRoute: DocsAdvancedArchitectureRoute,
  DocsAdvancedTroubleshootingRoute: DocsAdvancedTroubleshootingRoute,
  DocsApiRestRoute: DocsApiRestRoute,
  DocsApiSseRoute: DocsApiSseRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface MemoriesRouteChildren {
  MemoriesIdRoute: typeof MemoriesIdRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
}

const MemoriesRouteChildren: MemoriesRouteChildren = {
  MemoriesIdRoute: MemoriesIdRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
}

const MemoriesRouteWithChildren = MemoriesRoute._addFileChildren(
  MemoriesRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsNameRoute: typeof ProjectsNameRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsNameRoute: ProjectsNameRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  CheckpointsRoute: CheckpointsRoute,
  DocsRoute: DocsRouteWithChildren,
  GuideRoute: GuideRoute,
  McpRoute: McpRoute,
  MemoriesRoute: MemoriesRouteWithChildren,
  MetricsRoute: MetricsRoute,
  MultiAgentRoute: MultiAgentRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
